### ISSUE TITLE
perform stability selection

### ISSUE THREAD

**Issue by timflutre** [jchiquet/spring#6]
Charlotte needs it for her work, but didn't succeed in making it work, so I'll try and make a pull request if I succeed.

**Comment by timflutre** [comment]
I created a branch `stabsel` on my fork.

**Comment by timflutre** [comment]
Hi @jchiquet, 
I started to add some code to the vignette `basics.Rmd` to show how to use `stabsel` but an error remains, and I can't find the solution. It would be great if you had some time to look at it ([here](https://github.com/timflutre/spring/commit/2e954c813d09ba510bfc579a6e5641492c8c9d20)).

**Comment by jchiquet** [comment]
Hi, 

Though ugly, this seems to work...

```{r}
library(stabs)
set.seed(5678)
fitfunSpring <- function(x, y, q, ...){
  fit <- spring(x=x, y=y, comp.df = FALSE, verbose = FALSE, ...)[[1]]
  id_selected <- lapply(fit@coef.regres, function(x) which(rowSums(x) != 0))
  qvals <- sapply(lapply(fit@coef.regres, function(x) rowSums(x) != 0), sum)
  id_selected <- id_selected[qvals <= q]
  selected <- rep(FALSE, ncol(x))
  selected[id_selected[[length(id_selected)]]] <- TRUE
  
  path <- matrix(FALSE, ncol(x), length(id_selected))
  for(idx in seq_along(id_selected)) path[id_selected[[idx]], idx] <- TRUE
  rownames(path) <- colnames(as.data.frame(x))
  res <- list(selected = selected, path = path)
  res
}

stab.spring <- stabsel(x=X, y=as.matrix(Y),
                       PFER=1, B=4, q=2, mc.cores=1, # to debug
                       ## PFER=1, B=50, q=max(5, 14),#min(2 * round(nrow(X)/log(ncol(X))/10)*10, ncol(X))),
                       fitfun=fitfunSpring,
                       args.fitfun=list(lambda2 = 0, min.ratio = 0.5, nlambda1 = 20,
                                        struct = sparseMatrix(i=1:p, j=1:p,x=rep(1, p))))

plot(stab.spring, "spring stability path")
```

**Comment by timflutre** [comment]
Thanks! I'll look into this ASAP to include it in the `basics` vignette and make a pull request.

**Comment by jchiquet** [comment]
I already included my quick-and-dirty version in in the vignette (Basics.Rmd). But you think of something more elegant or some improvements, please be my guess !

**Comment by timflutre** [comment]
Ah ok, I didn't see it. No, it looks perfect!
